# REUSE.toml - SPDX REUSE 3.3 compliance for EU EOSC / FSFE
# https://reuse.software/spec/
version = 1
[[annotations]]
path = ["**/*.py", "**/*.js", "src/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Louis-Philippe Audette"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["README.md", "docs/**", "*.md", "index.html"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Louis-Philippe Audette"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["LICENSES/Apache-2.0.txt", "LICENSE"]
SPDX-FileCopyrightText = "2026 Louis-Philippe Audette"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["LICENSES/CC-BY-4.0.txt"]
SPDX-FileCopyrightText = "2026 Louis-Philippe Audette"
SPDX-License-Identifier = "CC-BY-4.0"
