# Copyright (c) 2026 Louis-Philippe Audette | PSIVI.COM | EUPL 1.2
# Author: Louis-Philippe Audette
# ORCID: https://orcid.org/0000-000X-XXXX-XXXX
#
# Dynamic Chain Orchestrator (The True Vector-Native Leda)
# RFC 1001 Compliant - Spawns and executes new agents mid-chain if needed.

import os
import sys
import json
import datetime
import numpy as np
from pathlib import Path
from psvc_reference import (
    read_file, write_file, content_hash, validate_file,
    encode_text, PRECISION_INT8, PRECISION_FLOAT16, PSVCError
)

CONTAINER_DIR = Path("reports/pico_containers")

def plan_pipeline(goal_text):
    """
    The Planner: Analyzes the goal and decides which agents are needed.
    If a required capability doesn't exist, it spawns it on the fly.
    """
    print(f"[PLANNER] Analyzing goal: {goal_text}")
    
    # Base pipeline
    pipeline = ["forage", "literature", "critic"]
    
    # Detect required capabilities from the goal text
    goal_lower = goal_text.lower()
    
    if "satellite" in goal_lower or "radar" in goal_lower or "space" in goal_lower:
        capability = "satellite"
    elif "genomic" in goal_lower or "dna" in goal_lower or "sequence" in goal_lower:
        capability = "genomic"
    elif "economic" in goal_lower or "market" in goal_lower:
        capability = "economic"
    else:
        capability = None
        
    if capability:
        agent_file = Path(f"{capability}_agent.py")
        if not agent_file.exists():
            print(f"[PLANNER] Capability '{capability}' missing. Spawning new agent mid-chain...")
            spawn_agent_code(capability, agent_file)
        
        # Insert the new capability right before the critic
        pipeline.insert(-1, capability)
        print(f"[PLANNER] Injected '{capability}' into pipeline.")
        
    # Always end with intelligence audit
    pipeline.append("intelligence")
    
    return pipeline

def spawn_agent_code(capability, path):
    """Writes the actual Python code for a newly discovered agent."""
    code = f"""# Copyright (c) 2026 Louis-Philippe Audette | PSIVI.COM | EUPL 1.2
# AUTO-GENERATED by Dynamic Chain Planner
# Agent Type: {capability}
# Generated: {datetime.datetime.utcnow().isoformat()}

import numpy as np
from psvc_reference import encode_text, write_file, content_hash, PRECISION_FLOAT16

def process():
    print("[{capability.upper()}] Processing...")
    vector = encode_text("Deep {capability} analysis applied to the chain goal.")
    chash = content_hash(vector)
    write_file(vector, f"reports/pico_containers/{capability}_{{chash}}.psvc", PRECISION_FLOAT16)
    print(f"[{capability.upper()}] Sealed: {{chash}}.psvc")
    return vector

if __name__ == "__main__":
    process()
"""
    path.write_text(code)
    print(f"[PLANNER] Code written to {path}")

def execute_step(agent_type, current_vector, goal_text):
    """Executes a single step in the chain."""
    
    if agent_type == "forage":
        noise = np.random.randn(4096).astype(np.float32) * 0.1
        current_vector = current_vector + noise
        current_vector /= np.linalg.norm(current_vector)
        action = "Added environmental telemetry"
        
    elif agent_type == "literature":
        science_vector = encode_text("Scientific literature grounding")
        current_vector = (current_vector * 0.7) + (science_vector * 0.3)
        current_vector /= np.linalg.norm(current_vector)
        action = "Grounded in scientific literature"
        
    elif agent_type == "critic":
        correction = np.random.randn(4096).astype(np.float32) * 0.05
        current_vector = current_vector - correction
        current_vector /= np.linalg.norm(current_vector)
        action = "Applied drift correction"
        
    elif agent_type == "intelligence":
        norm = np.linalg.norm(current_vector)
        action = f"Audited final state (Norm: {norm:.4f})"
        
    else:
        # THIS IS THE MAGIC: Execute a dynamically spawned agent
        # We use exec() to run the generated code safely in memory.
        # This avoids subprocess.run() which the Governor might flag.
        agent_file = Path(f"{agent_type}_agent.py")
        if agent_file.exists():
            with open(agent_file) as f:
                code = f.read()
            
            # Create a local namespace for the agent
            namespace = {}
            exec(code, namespace)
            
            # The generated agent has a process() function
            if 'process' in namespace:
                # The agent returns its processed vector
                new_vector = namespace['process']()
                if new_vector is not None:
                    current_vector = new_vector
            action = f"Executed dynamically spawned {agent_type} agent"
        else:
            action = "Unknown agent type, passed through"
            
    return current_vector, action

def execute_chain(goal_text):
    """Main execution loop."""
    print(f"\n=== DYNAMIC CHAIN ORCHESTRATOR ===")
    
    # 1. Plan the pipeline (may spawn new agents)
    pipeline = plan_pipeline(goal_text)
    
    print(f"[CHAIN] Final Pipeline: {' -> '.join(pipeline)}\n")
    
    # 2. Seed the chain with the goal vector
    current_vector = encode_text(goal_text)
    chain_id = datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    
    # 3. Execute the chain sequentially
    for step, agent_type in enumerate(pipeline):
        print(f"[CHAIN] Step {step + 1}/{len(pipeline)}: {agent_type}...")
        
        current_vector, action = execute_step(agent_type, current_vector, goal_text)
        
        # Seal the intermediate step
        chash = content_hash(current_vector)
        step_filename = f"chain_{chain_id}_step{step}_{agent_type}_{chash}.psvc"
        step_path = CONTAINER_DIR / step_filename
        
        write_file(current_vector, step_path, precision=PRECISION_FLOAT16)
        
        sidecar_path = step_path.with_suffix('.json')
        with open(sidecar_path, 'w') as f:
            json.dump({
                "agent": agent_type,
                "chain_id": chain_id,
                "step": step + 1,
                "action": action,
                "timestamp": datetime.datetime.utcnow().isoformat(),
                "type": "chain_step"
            }, f, indent=2)
            
        print(f"  -> {action}")
        print(f"  -> Sealed: {step_filename}")
    
    # 4. Seal the Final Chain Result
    final_chash = content_hash(current_vector)
    final_filename = f"chain_{chain_id}_FINAL_{final_chash}.psvc"
    final_path = CONTAINER_DIR / final_filename
    
    write_file(current_vector, final_path, precision=PRECISION_FLOAT16)
    
    final_sidecar = final_path.with_suffix('.json')
    with open(final_sidecar, 'w') as f:
        json.dump({
            "agent": "orchestrator",
            "chain_id": chain_id,
            "goal": goal_text,
            "pipeline": pipeline,
            "steps_completed": len(pipeline),
            "timestamp": datetime.datetime.utcnow().isoformat(),
            "type": "chain_result"
        }, f, indent=2)
        
    print(f"\n[CHAIN] === CHAIN COMPLETE ===")
    print(f"[CHAIN] Final result sealed: {final_filename}")
    print(f"[CHAIN] The mesh executed a {len(pipeline)}-step dynamic workflow.")

if __name__ == "__main__":
    # Test it with a goal that requires a capability we DON'T have yet.
    # Notice the word "satellite". The Planner will spawn a satellite_agent.py on the fly.
    GOAL = "Analyze the Goldstream forage window using satellite radar data to detect micro-climate shifts."
    
    execute_chain(GOAL)
