name: Bulk Pin Actions

on:
  workflow_dispatch:

permissions:
  contents: write
  workflows: write

jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      
      - name: Run Python Script
        run: python3 pin_actions.py
        
      - name: Commit Changes
        run: |
          git config user.name "Wendy-Bot"
          git config user.email "bot@psivi.com"
          git add .github/workflows/
          git commit -m "chore: bulk pin actions to secure SHAs" || true
          git push || true
