name: build-docs
on:
  push:
    branches: [main]
    paths: ['docs/*.md']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1

      - name: Convert osdmp.md -> osdmp.html
        run: |
          # This takes your docs/osdmp.md and creates docs/osdmp.html
          # -s = standalone html, with title
          pandoc docs/osdmp.md -s --metadata title="OSDMP - psivi.com" -o docs/osdmp.html
          # Add SPDX header so REUSE stays compliant
          sed -i '1i<!-- SPDX-License-Identifier: CC-BY-4.0 -->' docs/osdmp.html

      - name: Commit back the html
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-build osdmp.html from md [skip ci]"
          file_pattern: docs/osdmp.html
